// Generated by gencpp from file motor_positions/positionArray.msg
// DO NOT EDIT!


#ifndef MOTOR_POSITIONS_MESSAGE_POSITIONARRAY_H
#define MOTOR_POSITIONS_MESSAGE_POSITIONARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <motor_positions/motorPosition.h>

namespace motor_positions
{
template <class ContainerAllocator>
struct positionArray_
{
  typedef positionArray_<ContainerAllocator> Type;

  positionArray_()
    : positions()  {
    }
  positionArray_(const ContainerAllocator& _alloc)
    : positions(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::motor_positions::motorPosition_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::motor_positions::motorPosition_<ContainerAllocator> >::other >  _positions_type;
  _positions_type positions;





  typedef boost::shared_ptr< ::motor_positions::positionArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motor_positions::positionArray_<ContainerAllocator> const> ConstPtr;

}; // struct positionArray_

typedef ::motor_positions::positionArray_<std::allocator<void> > positionArray;

typedef boost::shared_ptr< ::motor_positions::positionArray > positionArrayPtr;
typedef boost::shared_ptr< ::motor_positions::positionArray const> positionArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motor_positions::positionArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motor_positions::positionArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace motor_positions

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'motor_positions': ['/home/charles/devel/ros/scarab/scarab_ros/src/motor_positions/ROS-msgs'], 'std_msgs': ['/home/charles/catkin_ws/install_isolated/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::motor_positions::positionArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motor_positions::positionArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motor_positions::positionArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motor_positions::positionArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motor_positions::positionArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motor_positions::positionArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motor_positions::positionArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7805484bdfb5d5d980ba4c097f4f9dcf";
  }

  static const char* value(const ::motor_positions::positionArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7805484bdfb5d5d9ULL;
  static const uint64_t static_value2 = 0x80ba4c097f4f9dcfULL;
};

template<class ContainerAllocator>
struct DataType< ::motor_positions::positionArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motor_positions/positionArray";
  }

  static const char* value(const ::motor_positions::positionArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motor_positions::positionArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motorPosition[] positions\n"
"\n"
"================================================================================\n"
"MSG: motor_positions/motorPosition\n"
"uint8  motor_id\n"
"uint16 position\n"
;
  }

  static const char* value(const ::motor_positions::positionArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motor_positions::positionArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.positions);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct positionArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motor_positions::positionArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::motor_positions::positionArray_<ContainerAllocator>& v)
  {
    s << indent << "positions[]" << std::endl;
    for (size_t i = 0; i < v.positions.size(); ++i)
    {
      s << indent << "  positions[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::motor_positions::motorPosition_<ContainerAllocator> >::stream(s, indent + "    ", v.positions[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOTOR_POSITIONS_MESSAGE_POSITIONARRAY_H
