classdef motorPosition < robotics.ros.Message
    %motorPosition MATLAB implementation of motor_positions/motorPosition
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2020 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'motor_positions/motorPosition' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '791e891bae681c33af37a246f28f5485' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Dependent)
        MotorId
        Position
    end
    
    properties (Constant, Hidden)
        PropertyList = {'MotorId', 'Position'} % List of non-constant message properties
        ROSPropertyList = {'motor_id', 'position'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = motorPosition(msg)
            %motorPosition Construct the message object motorPosition
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function motorid = get.MotorId(obj)
            %get.MotorId Get the value for property MotorId
            motorid = typecast(int8(obj.JavaMessage.getMotorId), 'uint8');
        end
        
        function set.MotorId(obj, motorid)
            %set.MotorId Set the value for property MotorId
            validateattributes(motorid, {'numeric'}, {'nonempty', 'scalar'}, 'motorPosition', 'MotorId');
            
            obj.JavaMessage.setMotorId(motorid);
        end
        
        function position = get.Position(obj)
            %get.Position Get the value for property Position
            position = typecast(int16(obj.JavaMessage.getPosition), 'uint16');
        end
        
        function set.Position(obj, position)
            %set.Position Set the value for property Position
            validateattributes(position, {'numeric'}, {'nonempty', 'scalar'}, 'motorPosition', 'Position');
            
            obj.JavaMessage.setPosition(position);
        end
    end
    
    methods (Access = protected)
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.MotorId = obj.MotorId;
            cpObj.Position = obj.Position;
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.MotorId = strObj.MotorId;
            obj.Position = strObj.Position;
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.MotorId = obj.MotorId;
            strObj.Position = obj.Position;
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.motor_positions.motorPosition.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.motor_positions.motorPosition;
            obj.reload(strObj);
        end
    end
end
