classdef positionArray < robotics.ros.Message
    %positionArray MATLAB implementation of motor_positions/positionArray
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2020 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'motor_positions/positionArray' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '7805484bdfb5d5d980ba4c097f4f9dcf' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant, Access = protected)
        MotorPositionsMotorPositionClass = robotics.ros.msg.internal.MessageFactory.getClassForType('motor_positions/motorPosition') % Dispatch to MATLAB class for message type motor_positions/motorPosition
    end
    
    properties (Dependent)
        Positions
    end
    
    properties (Access = protected)
        Cache = struct('Positions', []) % The cache for fast data access
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Positions'} % List of non-constant message properties
        ROSPropertyList = {'positions'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = positionArray(msg)
            %positionArray Construct the message object positionArray
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function positions = get.Positions(obj)
            %get.Positions Get the value for property Positions
            if isempty(obj.Cache.Positions)
                javaArray = obj.JavaMessage.getPositions;
                array = obj.readJavaArray(javaArray, obj.MotorPositionsMotorPositionClass);
                obj.Cache.Positions = feval(obj.MotorPositionsMotorPositionClass, array);
            end
            positions = obj.Cache.Positions;
        end
        
        function set.Positions(obj, positions)
            %set.Positions Set the value for property Positions
            if ~isvector(positions) && isempty(positions)
                % Allow empty [] input
                positions = feval([obj.MotorPositionsMotorPositionClass '.empty'], 0, 1);
            end
            
            validateattributes(positions, {obj.MotorPositionsMotorPositionClass}, {'vector'}, 'positionArray', 'Positions');
            
            javaArray = obj.JavaMessage.getPositions;
            array = obj.writeJavaArray(positions, javaArray, obj.MotorPositionsMotorPositionClass);
            obj.JavaMessage.setPositions(array);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.Positions)
                obj.Cache.Positions = [];
                obj.Cache.Positions = obj.Positions;
            end
        end
    end
    
    methods (Access = protected)
        function resetCache(obj)
            %resetCache Resets any cached properties
            obj.Cache.Positions = [];
        end
        
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Clear any existing cached properties
            cpObj.resetCache;
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Recursively copy compound properties
            cpObj.Positions = copy(obj.Positions);
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            PositionsCell = arrayfun(@(x) feval([obj.MotorPositionsMotorPositionClass '.loadobj'], x), strObj.Positions, 'UniformOutput', false);
            obj.Positions = vertcat(PositionsCell{:});
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.Positions = arrayfun(@(x) saveobj(x), obj.Positions);
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.motor_positions.positionArray.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.motor_positions.positionArray;
            obj.reload(strObj);
        end
    end
end
