# CMake generated Testfile for 
# Source directory: /home/charles/devel/ros/scarab/scarab_ros/src/rosserial/rosserial_client
# Build directory: /home/charles/devel/ros/scarab/scarab_ros/build_isolated/rosserial_client
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_rosserial_client_gtest_float64_test "/home/charles/devel/ros/scarab/scarab_ros/build_isolated/rosserial_client/catkin_generated/env_cached.sh" "/usr/bin/python2" "/home/charles/catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/charles/devel/ros/scarab/scarab_ros/build_isolated/rosserial_client/test_results/rosserial_client/gtest-float64_test.xml" "--return-code" "/home/charles/devel/ros/scarab/scarab_ros/devel_isolated/rosserial_client/lib/rosserial_client/float64_test --gtest_output=xml:/home/charles/devel/ros/scarab/scarab_ros/build_isolated/rosserial_client/test_results/rosserial_client/gtest-float64_test.xml")
set_tests_properties(_ctest_rosserial_client_gtest_float64_test PROPERTIES  _BACKTRACE_TRIPLES "/home/charles/catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;143;add_test;/home/charles/catkin_ws/install_isolated/share/catkin/cmake/test/gtest.cmake;89;catkin_run_tests_target;/home/charles/catkin_ws/install_isolated/share/catkin/cmake/test/gtest.cmake;28;_catkin_add_google_test;/home/charles/devel/ros/scarab/scarab_ros/src/rosserial/rosserial_client/CMakeLists.txt;14;catkin_add_gtest;/home/charles/devel/ros/scarab/scarab_ros/src/rosserial/rosserial_client/CMakeLists.txt;0;")
add_test(_ctest_rosserial_client_gtest_subscriber_test "/home/charles/devel/ros/scarab/scarab_ros/build_isolated/rosserial_client/catkin_generated/env_cached.sh" "/usr/bin/python2" "/home/charles/catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/charles/devel/ros/scarab/scarab_ros/build_isolated/rosserial_client/test_results/rosserial_client/gtest-subscriber_test.xml" "--return-code" "/home/charles/devel/ros/scarab/scarab_ros/devel_isolated/rosserial_client/lib/rosserial_client/subscriber_test --gtest_output=xml:/home/charles/devel/ros/scarab/scarab_ros/build_isolated/rosserial_client/test_results/rosserial_client/gtest-subscriber_test.xml")
set_tests_properties(_ctest_rosserial_client_gtest_subscriber_test PROPERTIES  _BACKTRACE_TRIPLES "/home/charles/catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;143;add_test;/home/charles/catkin_ws/install_isolated/share/catkin/cmake/test/gtest.cmake;89;catkin_run_tests_target;/home/charles/catkin_ws/install_isolated/share/catkin/cmake/test/gtest.cmake;28;_catkin_add_google_test;/home/charles/devel/ros/scarab/scarab_ros/src/rosserial/rosserial_client/CMakeLists.txt;15;catkin_add_gtest;/home/charles/devel/ros/scarab/scarab_ros/src/rosserial/rosserial_client/CMakeLists.txt;0;")
add_test(_ctest_rosserial_client_gtest_time_test "/home/charles/devel/ros/scarab/scarab_ros/build_isolated/rosserial_client/catkin_generated/env_cached.sh" "/usr/bin/python2" "/home/charles/catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/charles/devel/ros/scarab/scarab_ros/build_isolated/rosserial_client/test_results/rosserial_client/gtest-time_test.xml" "--return-code" "/home/charles/devel/ros/scarab/scarab_ros/devel_isolated/rosserial_client/lib/rosserial_client/time_test --gtest_output=xml:/home/charles/devel/ros/scarab/scarab_ros/build_isolated/rosserial_client/test_results/rosserial_client/gtest-time_test.xml")
set_tests_properties(_ctest_rosserial_client_gtest_time_test PROPERTIES  _BACKTRACE_TRIPLES "/home/charles/catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;143;add_test;/home/charles/catkin_ws/install_isolated/share/catkin/cmake/test/gtest.cmake;89;catkin_run_tests_target;/home/charles/catkin_ws/install_isolated/share/catkin/cmake/test/gtest.cmake;28;_catkin_add_google_test;/home/charles/devel/ros/scarab/scarab_ros/src/rosserial/rosserial_client/CMakeLists.txt;16;catkin_add_gtest;/home/charles/devel/ros/scarab/scarab_ros/src/rosserial/rosserial_client/CMakeLists.txt;0;")
subdirs("gtest")
