set(_CATKIN_CURRENT_PACKAGE "motor_positions")
set(motor_positions_VERSION "0.0.0")
set(motor_positions_MAINTAINER "charles <charles@todo.todo>")
set(motor_positions_PACKAGE_FORMAT "2")
set(motor_positions_BUILD_DEPENDS "message_generation" "roscpp" "rospy")
set(motor_positions_BUILD_EXPORT_DEPENDS "message_generation" "roscpp" "rospy")
set(motor_positions_BUILDTOOL_DEPENDS "catkin")
set(motor_positions_BUILDTOOL_EXPORT_DEPENDS )
set(motor_positions_EXEC_DEPENDS "message_runtime" "roscpp" "rospy")
set(motor_positions_RUN_DEPENDS "message_runtime" "roscpp" "rospy" "message_generation")
set(motor_positions_TEST_DEPENDS )
set(motor_positions_DOC_DEPENDS )
set(motor_positions_URL_WEBSITE "")
set(motor_positions_URL_BUGTRACKER "")
set(motor_positions_URL_REPOSITORY "")
set(motor_positions_DEPRECATED "")